### ISSUE TITLE
Not Start

### ISSUE THREAD

**Issue by 66hrs** [lry127/Android-Hysteria-2-client#1]
Hi there
I installed and imported the config then started the VPN but it stopped after 1 sec 
this config work fine on IOS and  Windows

**Comment by lry127** [comment]
It changed to the stopped state because the backend hysteria library failed to start. You mentioned that there was one second before the failure, it's likely the library did receive some response from your server but somehow failed to accept the response (for example, due to tls certificate expiry caused by the unsynchronized system clock). More details are needed to look into this problem, if you are willing to share them, feel free to get in touch with me on Telegram. (t.me/lry127)

**Comment by lry127** [comment]
Double check you have entered the correct domain name, port, password and sni info. They are the most common source of failures.
